settings:
  parallel: true

driver:
  name: docker

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6
    platform: rhel

- name: centos-7
  driver:
    image: centos:7

- name: fedora-22
  driver:
    image: fedora:22

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_repo]
