name             'cloudwatch-agent'
maintainer       'SDTechDev Dev Team'
maintainer_email 'dev@sdtechdev.com'
license          'Proprietary - All Rights Reserved'
description      'installs cloudwatch agent for custom statsd monitoring'
version          '0.0.1'
