rvm: 2.2

sudo: required

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=cacher-client-ubuntu-1404
  - INSTANCE=cacher-client-ubuntu-1204
  - INSTANCE=cacher-ng-ubuntu-1404
  - INSTANCE=cacher-ng-ubuntu-1204
  - INSTANCE=cacher-ng-client-ubuntu-1404
  - INSTANCE=cacher-ng-client-ubuntu-1204
  - INSTANCE=compile-time-ubuntu-1404
  - INSTANCE=compile-time-ubuntu-1204
  - INSTANCE=lwrps-ubuntu-1404
  - INSTANCE=lwrps-ubuntu-1204
  - INSTANCE=unattended-upgrades-ubuntu-1404
  - INSTANCE=unattended-upgrades-ubuntu-1204

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
